pipeline:
    name: jbuild
    identifier: jbuild
    projectIdentifier: tempwf
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: account.rngit
                repoName: jhttp
                build: <+input>
    stages:
        - stage:
              name: build
              identifier: build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.gcpsalescidemo
                          namespace: build
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: build
                                identifier: build
                                spec:
                                    connectorRef: account.Harness_Docker_Connector
                                    image: maven:3.5.2-jdk-8-alpine
                                    command: mvn clean package -DskipTests
