pipeline:
    name: jbuild
    identifier: jbuild
    projectIdentifier: tempwf
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: account.rngit
                repoName: jhttp
                build: <+input>
    stages:
        - stage:
              name: build
              identifier: build
              template:
                  templateRef: java_maven
                  versionLabel: Version1
        - stage:
              name: deploy
              identifier: deploy
              template:
                  templateRef: k8s_deploy
                  versionLabel: Version1
                  templateInputs:
                      type: Deployment
                      spec:
                          infrastructure:
                              environmentRef: <+input>
