pipeline:
    name: temp2
    identifier: temp2
    projectIdentifier: tempwf
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: account.rngit
                repoName: jhttp
                build: <+input>
    stages:
        - stage:
              name: build
              identifier: build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.gcpsalescidemo
                          namespace: build
                  execution:
                      steps:
                          - step:
                                name: temp2
                                identifier: temp2
                                template:
                                    templateRef: javamaven
                                    versionLabel: Version1
        - stage:
              name: deploy
              identifier: deploy
              template:
                  templateRef: k8s_deploy
                  versionLabel: Version1
                  templateInputs:
                      type: Deployment
                      spec:
                          infrastructure:
                              environmentRef: <+input>
