pipeline:
    name: teswasdf
    identifier: teswasdf
    projectIdentifier: tempwf
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: account.rngit
                repoName: jhttp
                build: <+input>
    stages:
        - stage:
              name: build
              identifier: build
              template:
                  templateRef: account.JavaMaven
                  versionLabel: Version1
                  templateInputs:
                      type: CI
                      spec:
                          execution:
                              steps:
                                  - step:
                                        identifier: restore_maven_cache
                                        type: RestoreCacheGCS
                                        spec:
                                            bucket: <+input>
